src/mediatype-icon.ts

```
<mediatype-icon 
.mediatype=${this.model?.mediatype}
?showText=${true}
style="--iconHeight: 10px; --iconWidth: 10px;"
>
</mediatype-icon>
```

Add width height mediatype icon

---

src/tiles/list/date-label.ts
src/tiles/list/tile-list-compact-header.ts
src/tiles/list/tile-list-compact.ts
src/tiles/list/tile-list.ts
src/utils/format-date.ts
test/utils/format-date.test.ts

DRY date-label method
Add display of date label + value if sorted on that date type in detailed list tile
Change short date format from 'yyyy' to 'Jan yyyy'

Date sort display, short date format

---

src/collection-browser.ts

Since this modifies the content of the cells, the infinite scroller needs to reload them to get the updated values

Reload the infinite scroller when baseImageUrl changes

---

demo/app-root.ts
src/collection-browser.ts
src/models.ts
src/tiles/item-image.ts

Our previous understanding of "deemphasize" has changed.
The collection `loggedin` flags tiles to be blurred and a different warning for items depending if user logged in or not.
The collection `no-preview` flags a blur and content warning.
Moved determination of these states to model and added properties to model.
Created "Simulate Login" to allow testing in demo.

Add logged in and content warning to model

---

tsconfig.json
types/dompurify.d.ts
yarn.lock

problem: offshoot is not properly building bc the vendor package `dompurify` has an implicit type.
solution: make shim type file to declare it
acceptance: offshoot cleanly builds
note: 0.2.14-a1

Dompurify add vendor type

---

src/collection-browser.ts
test/collection-browser.test.ts

For dynamic updates, allow collection browser to rehydrate when loggedin property gets updated
- go to demo app: https://internetarchive.github.io/iaux-collection-browser/pr/pr-95/?query=collection%3Aloggedin
- toggle "simulate logged in state", note tile image covers go between login required & content warning
this allows demo to dynamically update given "simulate login checkbox"

collection browser, update when `loggedIn` updates

---

src/app-root.ts
src/collection-facets.ts
test/collection-facets.test.ts

Renders collection facet titles as links to their collection page.
Note that the links are domain-relative, so on the demo app they link to non-existent pages. They should be fine on archive.org though.

WEBDEV-5450 Convert collection facet titles to links

---

src/app-root.ts
src/collection-browser.ts
src/collection-facets.ts
src/tiles/tile-dispatcher.ts
src/utils/analytics-category-event.ts

Fires analytics events when patron clicks on facets, sorters, filters, view mode changes, and result clicks
updates: 
- update demo to show in control panel
- removes <collection-facet> analytics calls, opt for callback
- adds result click handler to fire analytic
- more granular events around de/selecting facets & their negative counterparts

Analytics updates

---

src/collection-facets.ts
src/collection-facets/more-facets-pagination.ts

when starting at 1, show 1 2 3 ... N
when under 7 pages, and selected on either [3, 4, 5, 6] => show all pages 1 2 3 4 5 6 7
at end, show prev 2
shows all pages if count is under 5

Morefacets pager updates

---

src/app-root.ts
src/collection-facets/facets-template.ts
src/collection-facets/more-facets-content.ts

Updates in this PR:
- in-repo demo app https://internetarchive.github.io/iaux-collection-browser/pr/pr-117/?query=beyonce
- Facet group alignment
- eye icon and checkbox line up so that when using negative facet, the tail of the eye icon does not go below the checkbox's baseline
- checkbox and eye icon are of height 15px
- this continues to allow text to grow while count, input & eye icon stays in place
- normalizing style for facet groups across views (desktop, mobile, more facets modal) & browsers (Safari, Chrome, FF)
- update demo to help Toggle show/hide of cell controls
- <img width="300" alt="image" src="https://user-images.githubusercontent.com/7840857/192441316-78a8f485-9b6d-4406-8da5-d2fe007bb69e.png"> <img width="300" alt="image" …

align checkbox w eye icon by setting the checkbox height/width, ++

---

src/restoration-state-handler.ts
test/restoration-state-handler.test.ts

When navigating to a URL that loads collection browser with `and[]` parameters, in certain cases it would throw an error from trying to set the state of facet buckets that didn't exist yet. This fix prevents those errors by constructing temporary facet buckets for the `and[]` parameters with the appropriate state, which will eventually be replaced by the real facet buckets (with correct count) once the search result aggregations load in.
Also adds a bunch of unit tests for the restoration state handler building its state based on the page URL, to prevent future regressions of this nature.

WEBDEV-5487 Fix errors reading facet state from URL params

---

src/collection-facets/facets-template.ts
src/collection-facets/more-facets-content.ts
src/tiles/list/tile-list.ts
src/utils/format-count.ts

- Each page displays 35 facets
- Desktop view for the modal:
- UI: Facets displays in 3 columns, modal has fixed height
- during paging, there is less vertical scrolling to view the facets on-page
- Mobile view
- UI: Facets displays in 1 scrollable column per page, modal has fixed height
- shrink width of modal to see facets displayed in 1 column.
- Scrollable facet group area:
- when the facet group area is scrollable, its scroll bar does not overlap on facet data
- Note: Modal has max height, will not shrink if window height reduces
- https://internetarchive.github.io/iaux-collection-browser/pr/pr-123/?query=collection%3Ainlibrary
- Check "Show Facet Group Outlines" checkbox - each facet group has red top border, blue bottom border
- Open "More..." **Collection** Facets
- ✅  when facets …

more facets tweak: 35 results/page, 1 col @560px, 3 col after WEBDEV-5489

---

src/collection-browser.ts
src/collection-facets.ts
test/collection-browser.test.ts

- Switching to full text search option shouldn't immediately clear More... facet links (it should wait until new search performed)
- Switching to a different search type should allow performing the same search query again with the new search type. Shouldn't have to change the search query.

WEBDEV-5501 Fix bugs on toggling search options

---

src/tiles/image-block.ts
src/tiles/list/tile-list-compact.ts
src/tiles/list/tile-list.ts
src/tiles/overlay/icon-overlay.ts
test/image-block.test.ts
test/tiles/list/tile-list-compact.test.ts

When logged out, the message should be "Log in to view this content" and the icon should be the login icon.
When logged in, the message should say "Content may be inappropriate" and the icon should be the caution triangle

Fix loggedIn icon overlay in grid and compact display mode

---

package.json
src/collection-browser.ts
yarn.lock

A handful of search result fields that we used to fetch from `advancedsearch.php` were initially not available on PPS result hits. However, these are now being served by the PPS and can be used to populate the tile models again.
- `addeddate`
- `avg_rating`
- `issue`
- `item_count`
- `source`
This PR reinstates support for these fields so that they appear correctly on result tiles/list items.

WEBDEV-5520 Reinstate previously-missing search result fields

---

src/collection-facets.ts
src/tiles/list/tile-list.ts

- go and search for `puppies`
- switch to list view
- note the link color is incorrect for links to “More…” facets, item titles, creators, topics, collections
- Color is #0000ee, should be #4b64ff
**Updated:**

WEBDEV-5518 Change all links color

---

src/collection-browser.ts
src/collection-facets.ts
src/collection-facets/more-facets-content.ts
src/models.ts
src/tiles/list/tile-list.ts
test/collection-facets.test.ts
test/tiles/list/tile-list.test.ts

Certain meta-collections (currently `deemphasize` and `community`) shouldn't be rendered in the facet sidebar or in item collection lists. This PR ensures such collections are not displayed in those two places.

WEBDEV-5513 Don't render certain collections as facets or list items

---

src/styles/item-image-styles.ts

- go search for `happy face`
- switch to list view display mode 
Note - this issue usually occurs when:
- there’s no default thumbnail/image is set in an item or it has the default IA logo with black background
- the thumbnail image is not 100px height size
**Previous:**
**New:**

WEBDEV-5512 Fix alignment of image and title text in listview mode

---

src/collection-browser.ts
test/collection-browser.test.ts
test/mocks/mock-search-responses.ts
test/mocks/mock-search-service.ts

The PPS now includes lending and year_histogram aggregations in the default list of aggregations, so these no longer need to be fetched separately. This PR makes use of these bundled aggregations and removes the old additional requests.

WEBDEV-5499: Merge all facet requests into a single request for the default list

---

package.json
src/app-root.ts
src/collection-browser.ts
src/restoration-state-handler.ts
test/collection-browser.test.ts
test/restoration-state-handler.test.ts
yarn.lock

This PR makes the restoration state handler load and save the `sin` param that determines the search type of a results page.
The demo app is also updated to make the dev tools panel more compact and readable, and to handle some other URL params that will allow easier testing of the search service through collection browser demos.

WEBDEV-5509 Add `sin` URL param to restoration state

---

src/collection-browser.ts
src/models.ts
src/tiles/list/tile-list-compact.ts
src/tiles/list/tile-list.ts
test/collection-browser.test.ts
test/tiles/list/tile-list-compact.test.ts
test/tiles/list/tile-list.test.ts

Items in both list view and compact view are incorrectly showing all-time view counts even when sorting by weekly views. This PR adds weekly views to the tile models and displays them on list items when sorting by weekly views.

WEBDEV-5532 Show weekly view counts on list items when sorting by them

---

src/collection-browser.ts
src/collection-facets/facets-template.ts
test/collection-facets/facets-template.test.ts

The big "Results" header should be title-cased (not all-caps) and it should be baseline-aligned with the result count (not center-aligned). The counts for facet buckets should also have the same localized formatting as the big result count (according to the user's browser default locale). This PR fixes these items.

WEBDEV-5537 Fix formatting on "Results" header and facet counts

---

src/tiles/grid/tile-stats.ts
src/tiles/mediatype-icon.ts

This PR ensures that tooltips for item stats (e.g., favorites, reviews, mediatype) have tooltips that describe the appropriate content of the item, not the icon shape.

WEBDEV-5540 Improve tooltips on grid/list items

---

src/collection-facets/facets-template.ts

Currently, clicking the label of a facet does nothing, despite it showing the interactive "pointer" cursor. This PR makes clicking on those labels behave the same as if the facet's checkbox were clicked.

WEBDEV-5541 Make clicking facet labels check their checkbox

---

src/collection-browser.ts
src/collection-facets.ts
src/collection-facets/facet-tombstone-row.ts

This PR hides the circular loading indicators when search results and facets are loading, and renders placeholder "tombstones" in place of facet buckets until they load in.

WEBDEV-5514 Show facet tombstones while facets are loading

---

src/collection-facets.ts
test/collection-facets.test.ts

With the facet tombstones update, there’s a placeholder block being shown for the date picker while it loads. However, when the date picker is disabled, that placeholder is confusing and shouldn’t show up. This PR ensures the facet tombstones do not include a placeholder block for the date picker when the feature is disabled.

WEBDEV-5546 Only show placeholder for date picker when it's enabled

---

src/tiles/list/tile-list.ts
test/tiles/list/tile-list.test.ts

Some links on list view tiles were still pointing to old search.php pages (e.g., creator links, subject links). These are updated by this PR to point to the new beta search page.

WEBDEV-5538 Upgrade list view tile links to point to beta search (not search.php)

---

src/app-root.ts
src/collection-browser.ts
test/collection-browser.test.ts
test/mocks/mock-search-responses.ts
test/mocks/mock-search-service.ts

Currently a separate PPS request is sent to obtain year histogram data for the date picker, regardless of whether the date picker is present on the page.
Moreover, the request that retrieves all the other facets also includes the year histogram data, which is correct as long as there are no year facets or date range filters applied. In those cases, there is no need for a separate year histogram request. The additional request is only necessary if the user has selected a year facet or specified a date range.
This PR ensures a separate year histogram facet request is only sent if the date picker is actually enabled and there is a selected year facet or a date range filter applied. It also refactors some of the facet-query-building getters to decouple the with-date query from the …

WEBDEV-5572 Only send separate year_histogram requests when necessary

---

src/collection-browser.ts

When going from a blank search (empty placeholder) to a new search, the “loading placeholder” tile tombstones appear while the results load, as expected. But if you perform another search after that, the tile tombstones don’t appear anymore – the old results stay up until the new ones arrive. So there’s no indication that results are loading.
This PR ensures the search results always show placeholder tombstones immediately upon performing a new search, regardless of whether or not there were other search results present beforehand.

WEBDEV-5549 Show placeholder tiles upon each new search performed

---

package.json
src/app-root.ts
src/collection-browser.ts
src/tiles/list/tile-list.ts
test/collection-browser.test.ts
test/mocks/mock-search-responses.ts
test/mocks/mock-search-service.ts
test/tiles/list/tile-list.test.ts
yarn.lock

These changes ensure that the tile model receives the full description value (which may be an array consisting of many lines), rather than just the first line. Then, when the description is rendered in extended list view, this PR ensures these line breaks are correctly rendered and each line is correctly sanitized. While only 3 lines of description will ever be visible in the tile preview, this ensures we are not prematurely truncating the preview at the first line break.
This PR also updates the demo app & search service version to avoid running into CORS errors when specifying a custom `search_base_url` (e.g., for testing against a review app).

WEBDEV-5567 Show 3-line descriptions

---

src/tiles/list/tile-list.ts
test/tiles/list/tile-list.test.ts

The list of collection links on tiles in extended list view should not include "user favorites" collections (`fav-<username>`). This PR ensures those collections are not rendered.

WEBDEV-5581 Hide fav- collections in list view tiles

---

src/collection-facets/facets-template.ts
src/tiles/list/tile-list.ts
test/tiles/list/tile-list.test.ts

Certain links on search tiles in extended list view point to new `/search` queries without `rel=nofollow`, causing crawlers to hit potentially many more search pages than desired.
Our links to collection details pages on collection facets are also not using `rel=nofollow`, which may have similar effects on crawlers.
This PR adds `rel=nofollow` to both of those types of links.

WEBDEV-5586 Add rel=nofollow links to search tile links and collection facets

---

src/tiles/item-image.ts
test/item-image.test.ts

Currently, if search result tiles are rendered before the page config has fully loaded, they may have an invalid `baseImageUrl` which they use to fetch their item image, resulting in many 404s for URLs containing `undefined`.
This PR adds a guard clause preventing these bad image requests from firing before the config (with correct `baseImageUrl`) has properly loaded.

WEBDEV-5599 Prevent item images from having undefined URLs

---

src/app-root.ts
src/collection-browser.ts
src/models.ts
src/sort-filter-bar/alpha-bar.ts
src/sort-filter-bar/sort-filter-bar.ts
test/collection-browser.test.ts
test/mocks/mock-search-responses.ts
test/mocks/mock-search-service.ts
test/sort-filter-bar/alpha-bar.test.ts
test/sort-filter-bar/sort-filter-bar.test.ts

On the legacy search page, when the alphabet filter bar is shown, letters which correspond to 0 items are grayed out and unclickable. This PR adds that functionality to the collection browser.

WEBDEV-5561 Disable/gray-out letters with 0 results in alphabet filter bar

---

src/collection-browser.ts
test/collection-browser.test.ts

This PR changes the "- Results" label to reflect the loading state by changing to "Searching..." when a new set of results is loading as a result of a query change. The data model (incl. results, total result count, and aggregations) is now also fully emptied as soon as a new search is performed, rather than persisting until the new search results arrive.

WEBDEV-5575 Clarify loading state and empty search data model on new search

---

src/collection-browser.ts

The page fetch logic currently assumes that when the last page of results loads in, it must represent the final page fetch. So it caps off the infinite scroller’s tile count with whatever count it currently has.
However, if the last couple of pages load out-of-order (e.g., page N arrives before page N-1), then this prematurely limits the number of items shown (page N-1 never shows up in the UI).
This is particularly problematic on [searches that have just over 50 items](https://internetarchive.github.io/iaux-collection-browser/main/?query=pro+archia+poeta) – if the second page of items arrives before the first, then only a few items will ever be shown, completely ignoring the first 50.
This PR addresses the issue by ensuring that the infinite scroller's item count is not capped off until …

WEBDEV-5620 Fix page fetch race condition that sometimes causes tiles not to load

---

package.json
src/app-root.ts
src/collection-browser.ts
src/collection-facets.ts
src/collection-facets/more-facets-content.ts
src/restoration-state-handler.ts
test/collection-browser.test.ts
test/collection-facets/more-facets-content.test.ts
test/restoration-state-handler.test.ts
yarn.lock

The PPS has a `filter_map` param for accepting facets and date picker ranges in a more structured way than jamming them all into the query string (which is what is currently done). The search service has recently been updated to handle this parameter.
This is an important prerequisite for having “correct” facet handling at the PPS level (i.e., omitting each facet group’s filters from its own facet queries).
This PR updates collection-browser's handling of facets and date ranges to rely on filter maps rather than joining all the query clauses itself.

WEBDEV-5605 Integrate search service filter map

---

src/tiles/grid/styles/tile-grid-shared-styles.ts
src/tiles/grid/tile-stats.ts

On Windows machines, the font that matches Helvetica by default does not allow more granular font weights than normal and bold. Since our new tile designs use a medium font weight between these two, Windows users would see the same font weight for item titles and creators, which gave a poor sense of visual hierarchy. Also, with the current line heights, descenders on some text lines are being cut off.
This PR fixes both of these problems by updating the font fallback stack to one that looks better on Windows, and adding a small bottom padding to certain lines of tile text to accommodate descenders.

WEBDEV-5648 Adjust tile typography for Windows and avoid clipping descenders

---

src/sort-filter-bar/sort-filter-bar.ts
test/sort-filter-bar/sort-filter-bar.test.ts

Resolves a bug in mobile view, where selecting a different sort option would still leave any existing title/creator letter filter active.

WEBDEV-5680 Ensure title/creator letter filters clear when mobile sort field changes

---

src/collection-browser.ts
test/collection-browser.test.ts

The `infiniteScroller` member of collection browser is incorrectly asserted to be non-null. This assertion is invalid in cases where the infinite scroller is not rendered, such as when showing a “0 results” or “no query” placeholder. As a result of the non-null assertion, there are several places in collection-browser.ts that assume `this.infiniteScroller` exists without tsc complaining, producing errors at runtime when that assumption fails (like in the case above).
This PR removes that non-null assertion and ensures uses of `this.infiniteScroller` are optional-chained or null-guarded as appropriate.

WEBDEV-5654 Ensure uses of infiniteScroller are properly null-guarded

---

src/styles/item-image-styles.ts
src/tiles/grid/item-tile.ts
src/tiles/grid/styles/tile-grid-shared-styles.ts
src/tiles/grid/tile-stats.ts
src/tiles/image-block.ts
src/tiles/text-snippet-block.ts

Removes some of the whitespace between lines on grid tiles, and ensures the stats row at the bottom is aligned consistently.

WEBDEV-5690 Adjust grid tile layout

---

src/tiles/list/date-label.ts
src/tiles/list/tile-list-compact-header.ts
src/tiles/list/tile-list-compact.ts

In the compact list view:
- Adds a "Type" column header to the column with the mediatype icons (since it looks strange without any header)
- Defaults the date column to show date published, not date archived (unless there is a date sort active, which takes precedence).

WEBDEV-5695 Correct compact list view headers & date column defaults

---

src/tiles/list/tile-list.ts
test/tiles/grid/account-tile.test.ts
test/tiles/list/tile-list.test.ts

Converts extended list view mediatype icons into links targeting their mediatype's collection details page.

WEBDEV-5694 Make mediatype icons in list view link to their collection

---

src/collection-browser.ts
src/tiles/grid/tile-stats.ts

Currently, at mobile device portrait view widths, often there is only one column of grid tiles shown, and the tiles appear overly wide.
This PR reduces the minimum widths of tiles at different breakpoints to ensure that they can continue to fit 2 columns even down to very narrow device widths. These smaller min widths also allow the tile columns to shrink further before a column is removed, which has the side effect of reducing the maximum tile width possible.

WEBDEV-5686 Ensure grid tiles are not overly wide, fit 2 cols in mobile view

---

index.html
src/tiles/image-block.ts

The container box around extended list view thumbnails blends in very closely with the background on archive.org, making it look like the aspect-fit thumbnails are misaligned when they are wider than they are tall. This PR adjusts the styles for the container box to make the box more visibly aligned with the title row.
Also gives the demo app the same color background as archive.org, to serve as a better point of comparison.

WEBDEV-5693 Adjust extended list view thumbnail styles for better visibility/alignment

---

src/collection-facets.ts
src/collection-facets/more-facets-content.ts
test/collection-facets.test.ts

The little sorting toggle buttons in the facet sidebar are confusing and unclear. There is already a means of sorting the facets within the More dialog, so the minor shortcut these buttons provide is not particularly helpful.
This PR removes those toggle buttons from the sidebar, and adjusts the sorting affordance in the More dialog to use a textual label describing the sort rather than the previous button's unclear visuals.

WEBDEV-5671 Remove facet sort toggles from sidebar, and convert to links in More dialog

---

src/tiles/list/tile-list.ts
test/tiles/list/tile-list.test.ts

Patches an issue with #188 where the links were not generating correctly in the production environment where `baseNavigationUrl` is an empty string.

WEBDEV-5717 Allow mediatype links with empty baseNavigationUrl

---

src/tiles/grid/styles/tile-grid-shared-styles.ts

Makes sure the date line appears at the top of its available space (like the creator line), not the bottom.

WEBDEV-5733 Fix date line positioning on grid tiles

---

src/sort-filter-bar/alpha-bar-tooltip.ts
src/sort-filter-bar/alpha-bar.ts
test/sort-filter-bar/alpha-bar-tooltip.test.ts
test/sort-filter-bar/alpha-bar.test.ts

The letters in the alphabet filter bar currently provide no visual feedback when hovered, making for a rather stale-feeling UI.
This PR brings the hover interaction closer to that of legacy search, darkening the background of the hovered letter and providing a tooltip with the number of results for that letter.

WEBDEV-5699 Add on-hover feedback to alphabet bar

---

src/tiles/grid/account-tile.ts
src/tiles/grid/collection-tile.ts
src/tiles/grid/item-tile.ts
src/tiles/grid/styles/tile-grid-shared-styles.ts
src/tiles/hover/hover-pane-controller.ts
src/tiles/tile-dispatcher.ts
test/tiles/grid/account-tile.test.ts
test/tiles/grid/collection-tile.test.ts
test/tiles/grid/item-tile.test.ts
test/tiles/tile-dispatcher.test.ts

The info popups that appear when hovering over grid tiles are currently not available to mobile/touch device users that don't have hover capability. To present an alternative for these users, this PR adds a small info icon in the corner of grid tiles when hover interactions are not available, which the user can tap to show/hide the info popup for that tile.

WEBDEV-5707 Allow info popups to be toggled by tapping info icon

---

src/collection-browser.ts
src/models.ts
src/tiles/list/tile-list.ts
src/tiles/tile-dispatcher.ts

On legacy search, FTS tiles include the current search query as a parameter when linking to items' details pages. This allows the theatre on the details page to perform its search-inside function when loaded. However, currently on the beta search page, FTS results don’t include this parameter.
The PPS provides an href field on FTS hits that includes the full link target, including the query string. Moreover, this field is intended to hold other contextual information (like start/end times) for TV/Radio hits when those are eventually enabled. So where possible, we should be making use of this field instead of constructing details page links manually.
This PR ensures that for FTS results (and other future result types), the tile links use the PPS href field that includes additional context …

WEBDEV-5737 Use PPS-provided href for tile links if available

---

src/collection-browser.ts
src/collection-facets.ts
src/collection-facets/more-facets-content.ts
test/collection-facets.test.ts

Way back when collection browser's results were backed by advancedsearch.php, there were some extra steps required to correctly filter on language facets. These entailed converting between human-readable language names and one or more corresponding language codes.
However, the PPS facet model requires that the facet keys passed in as filters exactly match those that were provided as aggregations, so it is no longer correct to perform these language name/code conversions. The PPS should be providing human-readable language names for facet buckets, and should accept those same human-readable language names as filters.
So, this PR removes the language code conversions from the facet logic, both for rendering facets and for applying filters. Two tests checking that language facets had these …

WEBDEV-5746 Remove special language facet handling as PPS no longer requires it

---

src/collection-browser.ts

Currently, items with etree mediatype are given special handling by the tile renderer. Their item titles, which are generally of the form `[Creator] Live at [Place] on [Date]`, are converted to the more concise `[Date]: [Place]` on the tiles.
For consistency’s sake going forward, we are removing this special handling so that the titles shown on the tiles always match the actual item’s title. Our new tiles have more space available for long titles than the legacy search ones, making it less important that they be short.

WEBDEV-5759 Remove special handling from etree item titles

---

src/tiles/list/tile-list-compact.ts
src/tiles/list/tile-list.ts
test/tiles/list/tile-list-compact.test.ts
test/tiles/list/tile-list.test.ts

To support users who rely on knowing which links they have visited from a search page, we should allow links to present their “visited” styling rather than forcing the blue color in all cases.

WEBDEV-5763 Allow links on extended & compact list view to use visited styling

---

package.json
src/collection-browser.ts
src/empty-placeholder.ts
yarn.lock

When a query results in an error on the backend, currently we either treat it the same as "0 results" or otherwise fail to act on it. This PR adds a third type of placeholder item for handling errors, with a link to the search help page and details about the error.

WEBDEV-5767 Provide proper error message when queries fail

---

src/collection-browser.ts
src/collection-facets.ts

The date picker no longer needs a feedback widget. This PR removes it.

Remove feedback widget from date picker

---

src/sort-filter-bar/sort-filter-bar.ts

For some browsers (esp. on Mac/iOS), the sort direction icons are rendering at their intrinsic size rather than fitting within the available space, causing them to not be visible. This PR restricts the height of those icon svgs to that of the sort bar, preventing the issue.

WEBDEV-5796 Ensure sort direction icon svg is properly sized on all supported browsers

---

src/tiles/list/tile-list.ts
src/tiles/text-snippet-block.ts
test/text-snippet-block.test.ts

Several blocks of metadata on list view tiles (esp. the description and full text snippets) are meant to be truncated after the first 3 lines. While this appears to be working across other browsers, Safari is not truncating them at all, which leads to excessively long walls of text in hover panes.
This PR introduces a wrapper element around these blocks of text that makes Safari truncate them properly.

WEBDEV-5800 Fix 3-line truncation of list tiles in Safari

---

src/collection-browser.ts
test/collection-browser.test.ts
test/mocks/mock-search-responses.ts
test/mocks/mock-search-service.ts

Search queries with leading or trailing spaces are currently being sent to the backend as-is. Although the backend trims the queries anyway, the response we get back consequently has a different query string than the one we sent. Currently, the tile renderer treats this query mismatch by ignoring what it assumes is an obsolete response to an old query, rendering nothing.
While the simple fix is just to trim the query, we can go one step further and mitigate future “query mismatch” issues of this nature by sending a `uid` parameter with each search request to the PPS. This parameter is not processed and should always be returned as-is on the response. If we maintain a consistent `uid` for queries that should be considered the same, then we can use this as a much better signal of …

WEBDEV-5785 Prevent query mismatch via uid param (and trim queries)

---

package.json
src/app-root.ts
src/collection-browser.ts
src/collection-facets.ts
src/collection-facets/more-facets-content.ts
src/models.ts
src/restoration-state-handler.ts
test/collection-browser.test.ts
test/restoration-state-handler.test.ts
yarn.lock

This PR simplifies how the search types are provided to collection browser from its parent component, so that requesting an additional search is no longer required. Search type changes due to history stack pops now correctly propagate upwards (e.g., to set the correct radio button option on the search page).

WEBDEV-5804 Correct handling of `sin` param

---

src/tiles/grid/item-tile.ts
src/tiles/list/tile-list-compact.ts
src/tiles/list/tile-list.ts
src/utils/format-date.ts
src/utils/local-date-from-utc.ts
test/tiles/grid/item-tile.test.ts
test/tiles/list/tile-list-compact.test.ts
test/tiles/list/tile-list.test.ts
test/utils/local-date-from-utc.test.ts

When items are uploaded with only a year in the date field, the search engine normalizes this to a date of Jan 1 at midnight. This normalized date is what gets returned on search queries, including those that we use for rendering tiles. So in these cases, tiles show an (incorrect) Jan 1 date published.
The legacy search page approached this by assuming that all dates occurring on Jan 1 at midnight should be just a raw year. This is likely true in most cases, though it also clobbers any “Jan 1 at midnight” date that an uploader actually intended.
This PR implements the same assumption as legacy search whenever it renders a date published on a result tile. So items with a normalized UTC date of Jan 1 at midnight (for any year) should only render it as a year, with no month/day. This is only …

WEBDEV-5810 Only show year when date published is Jan 1 at midnight

---

src/collection-browser.ts
src/collection-facets.ts
src/collection-facets/facets-template.ts
src/models.ts
test/collection-browser.test.ts
test/collection-facets/facets-template.test.ts

We had some facet analytics handlers added a while back, but it appears that they were never fully hooked up. This PR connects the wires so that clicks on facets trigger the desired analytics events.

WEBDEV-5786 Fix facet analytics not sending

---

index.html
src/app-root.ts
src/collection-browser.ts
src/collection-facets.ts

The facet sidebar is scrollable via mouse wheel (or similar), but shows no affordance indicating this. Moreover, it does not provide any easy way to scroll with input devices lacking a built-in scroll mechanism (e.g., old 2-button mouse with no wheel).
This PR adds a subtle scrollbar when hovering the sidebar to address both the discoverability and to allow scrolling via clicks only. It also adds a fade-out effect at the bottom of the sidebar whenever it is not scrolled to the bottom, indicating that there is more to view below.
Lastly, the column containing the facet sidebar was originally sized a way that flowed it off the bottom of the page, meaning that even with the sidebar scrolled all the way to the bottom, it was possible for its last few facet groups to be hidden until the rest …

WEBDEV-5803 Improve facet sidebar scroll discoverability & clamp to page height

---

src/empty-placeholder.ts

Search engine error messages that contain long words unbroken by whitespace, such as a long URL, currently overflow off the right side of the page. This PR just adds a style rule to make them wrap mid-word on these long strings if necessary.

WEBDEV-5806 Ensure long error messages wrap properly

---

src/collection-browser.ts
src/collection-facets/more-facets-content.ts
src/collection-facets/more-facets-pagination.ts
test/collection-browser.test.ts

This PR fixes a bug that prevented the alphabet bar's bucket counts from loading correctly when they were part of the initial query on page load (e.g., via a `firstTitle` or `firstCreator` filter in the URL). It also updates the requests for these counts to properly use the search service's filter map instead of joining `AND` clauses to the base query.

WEBDEV-5637 Ensure alphabet filter counts load when present on initial page load

---

package.json
src/collection-browser.ts
test/collection-browser.test.ts
test/mocks/mock-collection-name-cache.ts
test/mocks/mock-search-responses.ts
test/mocks/mock-search-service.ts
yarn.lock

Until recently, when we received collections on search hits & aggregations, we would only have the identifier for that collection and would need to make additional fetches to obtain its readable name. However, the PPS is now equipped with the ability to send all needed collection titles as part of the original hits/aggregations response.
This functionality is currently disabled behind a PPS flag, but will be enabled in the near future. In preparation, this PR checks whether the response includes collection titles, and if so it skips the additional step of fetching them. Otherwise, it will continue functioning as before.
When the flag is permanently enabled at the PPS end, we can take this one step further and remove the `collection-name-cache` dependency entirely.

WEBDEV-5842 Avoid collection title fetches when provided by original response

---

src/collection-browser.ts
test/collection-browser.test.ts

This PR supports the implementation of a loading indicator on the search page's "Go" button, by emitting an event whenever the `searchResultsLoading` state of the component changes.

WEBDEV-5829 Emit event when initial results loading state changes

---

src/collection-browser.ts
test/collection-browser.test.ts

Currently we make two separate page requests (for pages 1 and 2 of the results) on every query change, due to how the infinite scroller preloads a page ahead of the current one for smoother scrolling. However, it would be much easier on the search backend if these two pages were loaded together, rather than making two separate requests for them.
This PR allows initial page requests like these to be batched together and ensures that our initial page load only makes a single request for search results -- for **two** pages worth on that initial request. This only applies to the initial load of pages 1 and 2, _not_ to subsequent page loads.

WEBDEV-5576 Batch first two pages of results into a single request

---

src/collection-facets.ts

Lingering class attribute when opening 'more' on facets - causing sizing discrepancy for share modal

Share modal sizing

---

src/restoration-state-handler.ts
test/restoration-state-handler.test.ts

Context: for legacy compatibility reasons, collection-browser uses URL params containing square brackets to encode facet selection/negation, e.g., `and[]=subject:"foo"`. However, when these links are posted to Facebook (and possibly other PHP-based sites), these square brackets get altered to fill them with sequential numeric indices, e.g., `and[0]`, `and[1]`, ...
So a user who visits a search page link from Facebook always gets directed to a search with no facets selected, and a bunch of unrecognized params.
Since there's no indication Facebook is going to stop mangling links like this, we opt to be more lenient in what syntax we accept for these parameters. This PR updates the URL handling to recognize `and[]`/`not[]` parameters even if they have digits within their square brackets, and …

WEBDEV-5950 Recognize facet parameters that contain numbers within the key's square brackets

---

package.json
src/collection-browser.ts
src/collection-facets.ts
yarn.lock

At mobile widths, the date picker only takes up a fraction of the available space, making it small and hard to read.
While in desktop view we solved this by allowing it to expand into a larger modal, in the mobile layout it is possible to make the date picker wider all the time, no modal required. This PR allows it to fill the entire container width available to it in mobile view.
This also entails upgrading `histogram-date-range` component version, as the previous version has a bug causing it not to fully render updates to the component's `width`/`height` properties.

WEBDEV-5981 Make date picker full-width in mobile layout

---

src/tiles/list/tile-list.ts

Currently, clicking the mediatype icon on a list view tile opens that mediatype's collection in a new tab. This PR just makes it open in the same tab for consistency with all the other links on the page.

WEBDEV-5813 Mediatype icon links should open in the same tab

---

src/collection-browser.ts
src/utils/sha1.ts
test/collection-browser.test.ts

Currently the `uid` param that gets passed to the PPS on searches consists of the full query w/ all filters and sort options verbatim. That has made it a challenge to debug issues with search requests on the backend, so this PR produces a more easily traceable `uid` structured from short hashes and indicating the page requested, kind of request (hits, aggregations, or both), and the timestamp.

WEBDEV-5943 Use meaningful hashes for the `uid` param on search requests

---

src/collection-facets.ts
test/collection-facets.test.ts

Ensures that when the current search results include a `mediatype: collection` aggregation bucket, its facet is rendered in the sidebar regardless of its bucket count.

WEBDEV-6108 Always render `mediatype: collection` facet when present

---

src/collection-browser.ts
test/collection-browser.test.ts
test/mocks/mock-search-responses.ts
test/mocks/mock-search-service.ts

When the backend provides a tile `__href__` field for FTS queries, its values sometimes have erroneous ""doubly quoted"" clauses which cause subsequent search-within to fail. While there are more fundamental backend fixes in the works to address the source of those extra quotes, this PR provides a temporary fix to prevent them from affecting the rendered tile links.

WEBDEV-6122 Collapse double-wrapped quotes in tile href

---

index.ts
src/app-root.ts
src/collection-browser.ts
src/collection-facets.ts
src/collection-facets/facets-template.ts
src/empty-placeholder.ts
src/sort-filter-bar/alpha-bar.ts
src/tiles/list/tile-list-compact.ts
src/tiles/list/tile-list.ts
src/tiles/tile-dispatcher.ts
test/empty-placeholder.test.ts
test/tiles/grid/item-tile.test.ts
test/tiles/list/tile-list-compact.test.ts
test/tiles/list/tile-list.test.ts
test/utils/format-date.test.ts

To enable use on collection pages, the collection browser must be able to display the contents of a collection without any additional query set. The search service already allows this via `pageType=collection_details` with a valid `pageTarget` set to the collection identifier.
This PR adds the `withinCollection` prop to accept the collection identifier, passing it to the search service with the correct page type, and functioning correctly with an empty query in the presence of this additional prop.

WEBDEV-5910 Accept `withinCollection` prop with no query, for collection pages

---

src/collection-browser.ts
src/models.ts
src/sort-filter-bar/sort-filter-bar.ts
src/tiles/list/tile-list.ts
test/collection-browser.test.ts
test/mocks/mock-search-responses.ts
test/mocks/mock-search-service.ts

On collection pages, there may be a default sort applied to the results independent of the user's sort selection. For instance, most collections have a default sort of `week:desc` (this can be modified in collection metadata).
Accordingly, when browsing collection members, this default sort should be represented accurately in the sort bar UI. This PR slightly refactors how sort fields are handled, adding a `default` SortField enum member which indicates deferral to the current defaults (`relevance` if viewing a search results page, or the current collection's default if viewing a collection page).

WEBDEV-6176 Set default sort option from collection metadata

---

src/collection-browser.ts
src/collection-facets.ts
src/collection-facets/more-facets-content.ts
test/collection-facets/more-facets-content.test.ts

Currently, the More facet links are broken when searching within a collection (the dialog just hangs). This PR ensures the More facets search query uses the correct `page_type` and `page_target` params, fixing the issue.

WEBDEV-6209 Fix More facets within a collection

---

src/collection-browser.ts
src/models.ts
src/restoration-state-handler.ts
src/sort-filter-bar/sort-filter-bar.ts
test/restoration-state-handler.test.ts

Currently, one cannot set a sort option via URL if it does not appear in the sort bar -- collection browser clobbers these. So valid sorts like `avg_rating` are inaccessible. However, these were allowed on the legacy search page, and consequently there exist old links and possibly old bookmarks that include these now-unrecognized sort params.
To ensure these sort options continue to be available (even if not surfaced in the UI), this PR allows unrecognized sort options to be specified in the URL and passed as-is to the backend, which already has handling to determine whether they are valid.
Moreover, this PR includes a refactoring pass to clean up how various properties of sort options are handled internally, centralizing them into a single config instead of having several individual maps …

WEBDEV-6171 Handle unrecognized sort options

---

src/collection-browser.ts
src/models.ts
src/sort-filter-bar/sort-filter-bar.ts
test/collection-browser.test.ts
test/mocks/mock-search-responses.ts
test/mocks/mock-search-service.ts

Favorite collections should be sorted by Date Favorited by default. This option was not previously available, so this PR adds it and ensures it is applied as the default when browsing a `fav-*` collection.

WEBDEV-6237 Sort `fav-*` collections by Date Favorited

---

src/collection-browser.ts
test/collection-browser.test.ts

A bug introduced in #272 causes the collection page to clobber URL params such as the sort & facets when visiting a collection page that has a default sort. The cause of this was that a line which clears filters when the target collection is changed, which was not properly guarded to prevent it from running on the initial page load (i.e., when the target collection is changed from `undefined` to its initial value).
This PR addresses that bug and adds a suite of several tests designed to avert any further issues of this nature.

WEBDEV-6259 Ensure all URL params are respected on initial collection page load

---

src/collection-browser.ts
src/empty-placeholder.ts
test/collection-browser.test.ts
test/empty-placeholder.test.ts

Currently when the PPS request for a collection encounters an error, we are at best displaying an error message that implies something is wrong with the query (even when there isn't one), or at worst showing the "collection not found" state.
This PR adds a new placeholder option that should be somewhat more user-friendly, noting that the search engine couldn't load the collection details and linking to our support channel in case the problem persists.

WEBDEV-6256 Show more appropriate error message when collection fails to load

---

src/collection-browser.ts
test/collection-browser.test.ts

When the display mode changes, we require a full reload of the infinite scroller's cell contents, not just a refresh of the visible cell buffer. This undoes a slightly overzealous change in #278.

Fix an infinite scroller call that requires full reload, not just visible cell refresh

---

package.json
src/collection-browser.ts

dispatch an event to collection-page if resultcount is zero. The event will be listened at offshoot and switch to ?tab=about to show about page of collection.

Dispatch event to switch on ?tab=about tab when resultCount is 0

---

src/collection-browser.ts
src/tiles/base-tile-component.ts
src/tiles/tile-dispatcher.ts

When sorting by a type of date explicitly, the result tiles correctly show the corresponding date value in place of the creator line correctly and tiles should display the `defaultSort` if it's available within collection search
- load the demo app and search for `inlibrary` as collection query
- Date published is set as sortField param and the `published` text is displayed in the item-tile
- notice that the url didn't change with `?sort=` query param

Collection page tiles should still show date line when default sorting by a date

---

.github/workflows/gh-pages-main.yml

- update [gh-pages deploy action](https://github.com/JamesIves/github-pages-deploy-action) version
- make sure the generated gh-pages link is generated and when you load the page, the app is showing properly
----
**Note**: no need to update iaux-collection-browser version

Update gh-pages deploy action

---

src/collection-browser.ts

Adds a pair of properties that allow suppressing the empty-results placeholders and the result count / "Searching..." box, so that these can be hidden for an empty list.
Also adds a named slot above the infinite scroller, to allow inserting a message when a list is empty.

WEBDEV-6423 Empty list state

---

src/collection-browser.ts
src/collection-facets/facet-row.ts
src/collection-facets/facets-template.ts
src/models.ts
test/collection-browser.test.ts
test/collection-facets.test.ts
test/collection-facets/facet-row.test.ts
test/collection-facets/facets-template.test.ts

Currently our lowest-level facet component renders an entire _group_ of facets, making some of the facet logic and state management more complex than it needs to be. In order to simplify efforts to tweak facet behavior going forward, this PR extracts a new component to represent an individual facet row, providing a cleaner separation between the responsibilities of that single facet vs. those of the facet group as a whole. It also fleshes out our tests for a few facet behavior corners that were lacking test coverage before.

WEBDEV-6386 Refactor facets to extract individual facet row component

---

src/app-root.ts
src/collection-browser.ts
test/collection-browser.test.ts

Adds a `suppressFacets` property to collection-browser to allow quick disabling of the facets pane and its associated PPS requests.

Add prop to suppress facets pane & associated requests

---

src/sort-filter-bar/sort-filter-bar.ts

Currently we are using slot for loans tab sort-bar from offshoot. There are resizeObserver was using on universal sort filter-bar elements which is not present when loans tab. So applied check to make sure the element are there before .addObserver.
This fix is part of https://webarchive.jira.com/browse/WEBDEV-6481 ticket. This issue should be fixed when we added slot for loans tab sort filter-bar.

Fixed resizeObserver issue when you are on ?tab=loans

---

src/data-source/collection-browser-data-source.ts
test/collection-browser.test.ts
test/sort-filter-bar/sort-filter-bar.test.ts

- Fix Test `<sort-filter-bar>`: Resize Observer breaks when toggling between default view & custom slotted view
- Mute Tests `<collection-browser>`:
- `removeCheckedItems` are not working as expected from unit test level
- `placeholderType` not setting properly
- skipped a couple of tests because elemental order has broken some

Unit Tests Updates

---

src/sort-filter-bar/sort-filter-bar.ts
test/sort-filter-bar/sort-filter-bar.test.ts

This PR tweaks the sort selection dropdowns for Views/Dates so that:
1. After making a dropdown selection, changing the sort to something outside of that dropdown will leave the last selected option visible (i.e., "sticky" selection), instead of resetting the dropdown to its default state.
2. When no dropdown selection has been made yet (so the default option is visible on the dropdown label), opening the dropdown menu will correctly show that default option as the selected menu item. (Without this fix, the menu is opening in an indeterminate state with nothing selected.)

WEBDEV-6637 Ensure sort dropdown selections are sticky and correctly reflect active defaults

---

src/collection-browser.ts
src/data-source/collection-browser-data-source-interface.ts
src/data-source/collection-browser-data-source.ts
test/collection-browser.test.ts
test/data-source/collection-browser-data-source.test.ts

Adds a new property `suppressResultTiles` which, when true, causes no result tiles to be rendered into the infinite scroller. Used on the profile page for the case of displaying an empty user list.

WEBDEV-6469 Expose property to suppress display of results scroller

---

src/collection-browser.ts
src/restoration-state-handler.ts
src/sort-filter-bar/sort-filter-bar.ts

Fixes a bug introduced in #343 where changing the `defaultSortField` alone would incorrectly leave any previous view/date dropdown selection untouched if using the defaults. The correct behavior is to update the dropdown selection when _either_ the selected sort _or_ its default changes.

WEBDEV-6637 Ensure sort bar dropdowns update on default sort change

---

src/app-root.ts
src/collection-browser.ts
src/sort-filter-bar/sort-filter-bar.ts
test/collection-browser.test.ts
test/sort-filter-bar/sort-filter-bar.test.ts

Replaces the existing `isLoansTab` property with a more general `enableSortOptionsSlot` property that performs the same role, albeit with a purpose that is transparently more general. This option, like `isLoansTab` before it, serves only to indicate that a customizable slot should be rendered in the sort bar in place of the usual sorting options.
The sort bar CSS is slightly tweaked to ensure that the layout does not have undesired changes when this option is enabled without assigning anything to the resulting slot -- which is the case when we only wish to omit the sort options without replacement, as on the Web Archives tab of the profile page.

WEBDEV-6640 Generalize loan bar slot to permit broader customization

---

src/collection-browser.ts

when adding property with JS and not through lit template, we need property to be public.
[see job](https://git.archive.org/www/offshoot/-/jobs/719176)

open analytics handler

---

package.json
src/data-source/collection-browser-data-source-interface.ts
src/data-source/collection-browser-data-source.ts
test/mocks/mock-search-responses.ts
yarn.lock

Responses from the PPS generally include a `session_context` branch containing info about the user session within which the response was generated. Notably, it includes whether the user has privs which should permit them to perform full-text searches even in the absence of public (i.e., not `noindex`) items with searchable text.
This PR adds support for that session context and makes it available in the data source.

WEBDEV-6697 Extract session context from search service responses

---

src/collection-browser.ts
src/data-source/collection-browser-data-source.ts
src/manage/manage-bar.ts

When tiles are removed from view (e.g., by removing one's own uploads/favorites), the data source updates its tile offset accordingly to keep data pages aligned. This PR fixes a couple of bugs in data source methods that did not take the offset into account when converting b/w tile models & indices.

WEBDEV-6681 Fix offsets when tiles are removed

---

src/collection-browser.ts
src/collection-facets.ts
src/collection-facets/more-facets-content.ts
src/data-source/collection-browser-data-source.ts
test/collection-facets.test.ts
test/collection-facets/more-facets-content.test.ts

Ensures that profile-related params are propagated all the way through to the `<more-facets-content>` component to be used when fetching full facet lists.

WEBDEV-6738 Propagate profile params to more-facets component

---

src/sort-filter-bar/sort-filter-bar.ts

Fixes a bug where changing tabs on the profile page causes the sort bar to lose its resize behavior (i.e., it thereafter fails to switch between mobile/desktop layouts when resizing).

WEBDEV-6646 Ensure sort bar's resize observer is reinstalled after reconnected

---

src/data-source/collection-browser-data-source.ts

When removing checked tiles via collection-browser's management UI, currently the total result count next to the facets does not change. This PR fixes that bug to ensure the total result count reflects the removals immediately.

WEBDEV-6756 Update total result count when checked tiles are removed

---

src/app-root.ts
src/collection-browser.ts
src/data-source/collection-browser-data-source-interface.ts
src/data-source/collection-browser-data-source.ts
src/data-source/collection-browser-query-state.ts

Adds a bit of logic to the data source so that facets can be lazy-loaded when they are actually needed, avoiding expensive facet requests in cases where they are not (i.e., the majority of visits).

WEBDEV-6753 Allow facets to be lazy-loaded on demand in mobile view

---

src/collection-browser.ts

Since the analytics manager dependency can be injected after the first update cycle, it may not be available to send the layout size analytics. This patch ensures that in those cases, a subsequent update cycle will fire the analytics when the analytics manager becomes available.

WEBDEV-6826 Ensure layout size analytics send after analytics manager injected

---

src/collection-browser.ts

Currently if a visitor is using a tall/vertical screen that is capable of showing more than a single page of results at once, they will erroneously have a `page` param added to the URL that is one page ahead of their actual position. Most egregiously, this causes a `page=2` param to appear when they are at the top of the page, before scrolling at all.
This PR ensures that the current page indicated in the URL is never more than one page beyond that of the first visible cell.

Prevent page number from incrementing early on very tall screens

---

src/collection-browser.ts
src/collection-facets.ts
src/collection-facets/facet-row.ts
src/collection-facets/facets-template.ts
src/collection-facets/more-facets-content.ts
src/utils/facet-utils.ts
test/collection-browser.test.ts
test/collection-facets/facet-row.test.ts
test/collection-facets/facets-template.test.ts
test/collection-facets/more-facets-content.test.ts
test/mocks/mock-search-responses.ts
test/mocks/mock-search-service.ts

Currently facets in the More... dialog have the following behavior: when checked they immediately bubble up to the top of the page, and when unchecked they immediately return to their original sorted position. This behavior is similar to how facet selections bubble up to the top when selected in the _sidebar_, although the sidebar triggers a full refresh upon each selection while the dialog does not.
While the original intent was presumably to keep all the selected facets grouped separately from the unselected ones, the reflow upon making any facet changes is jarring and produces frustrating UX in many cases.
This PR adjusts the behavior in the dialog to leave facets in place when they are clicked, and performs a bit of cleanup & refactoring to improve some unusual data flows in our facet …

WEBDEV-6333 Don't move facets around when clicked in More... dialog

---

src/collection-facets/more-facets-content.ts

#381 introduced a performance bug where the page could hang upon selecting/deselecting facets in cases where the More facet list was very long. This PR patches the performance issue.

WEBDEV-6333 Bugfix for performance issue when facets are selected in very long lists

---

src/collection-facets/more-facets-content.ts

As of #381, the More facet dialog appears to have a bug where selecting facets, cancelling the dialog, then reopening it leaves them selected. If the second dialog was opened on a different facet type than the first one, then those selections are not visible but will still be applied along with the others. This PR fixes that bug by ensuring the selections are cleared when the dialog is cancelled.

WEBDEV-6333 Fix bug where unapplied facet selections can persist after cancelling More dialog

---

src/collection-browser.ts
src/data-source/collection-browser-data-source.ts
src/models.ts

This PR adds a new `opt-in-or-login` facet load strategy which works like `opt-in` for anyone who is not logged into an account, but like `eager` for anyone who is logged in. In other words, it treats being logged in as an automatic opt-in for facet production.
Moreover, when the facet load strategy changes from any non-eager strategy to `'eager'`, any pending delayed facet fetch is supposed to go ahead immediately. However, currently no facet fetch is made in that scenario. This PR patches the bug to make that fetch.

WEBDEV-6944 Add `opt-in-or-login` facet load strategy and related bugfix

---

src/collection-browser.ts
src/data-source/collection-browser-data-source.ts
src/data-source/collection-browser-query-state.ts
src/tiles/base-tile-component.ts
src/tiles/grid/item-tile.ts
src/tiles/grid/tile-stats.ts
src/tiles/list/tile-list-compact-header.ts
src/tiles/list/tile-list-compact.ts
src/tiles/list/tile-list.ts
src/tiles/tile-dispatcher.ts
test/collection-browser.test.ts

When viewing a collection that has a default sort set, the tiles are being sorted correctly but they fail to change the stats shown according to the default sort. For instance, when weekly views is the default (as it is for most collections), the tile stats still show the All-time Views rather than the Weekly Views amount. And when the default is a type of date, the creator line is not being replaced with a date line like it is supposed to.
This PR addresses some logic errors in how default sort params were being constructed & passed around, and ensures that the tiles display the correct info depending on the _effective_ sort (whether explicitly set or defaulted).

WEBDEV-6918 Fix tile display for default sorted collections

---

package.json
yarn.lock

We use the `madge` package to detect circular dependencies in our build step. One of `madge` v5's subdependencies balks when used in a node >=18 environment, so this PR upgrades it to v7 to address that issue.

Upgrade madge dep to v7 to address a node version incompatibility in its tree

---

package.json
src/models.ts
src/restoration-state-handler.ts
yarn.lock

Adds support in the restoration state handler for `sin=RADIO` being read from/written to the URL. This is to support radio searches being performed entirely within Offshoot rather than redirecting away to a legacy page.

WEBDEV-6909 Ensure radio searches are properly read/written to URL

---

.github/workflows/ci.yml

Our existing means of uploading coverage reports to codecov has been deprecated and superseded by the codecov-action GH action. This PR updates our CI workflow to rely on the new action.

Update CI to use newer codecov action

---

package.json
yarn.lock

Bumps `dompurify` to latest version `3.1.7` and `@types/dompurify` to latest version `3.0.5`.

Upgrade dompurify version to latest

---

src/collection-browser.ts
src/data-source/collection-browser-data-source.ts

Broadens the conditions under which the infinite scroller's results will be refreshed, to always include the initial page of results (even when multiple pages are being loaded in simultaneously).

WEBDEV-7022 Ensure initial page of results always triggers scroller refresh

---

src/collection-browser.ts
src/data-source/collection-browser-data-source.ts
test/collection-browser.test.ts

Fixes a bug where clearing a search query would not update the page URL accordingly in some cases. Simultaneously addresses a bug that impacted related tests, whereby the initial search promise could resolve too early due to a race condition.

WEBDEV-7150 Ensure cleared query propagates to data source & URL

---

src/utils/format-date.ts
test/utils/format-date.test.ts

Currently the date published shown on result tiles can be off by one for older years that fall before the creation of the local time zone, due to quirks in how dates are interpreted. This PR fixes the display error by ensuring that year-only dates always refer to UTC and do not involve the local time zone.

WEBDEV-7261 Fix discrepancy affecting old year-only publish dates

---

package.json
src/app-root.ts
src/collection-browser.ts
src/manage/manage-bar.ts
src/manage/remove-items-modal-content.ts
src/models.ts
test/manage/manage-bar.test.ts
test/manage/remove-items-modal-content.test.ts

https://webarchive.jira.com/browse/WEBDEV-7228

Consolidated Item Removal process which can be used on offshoot pages.

---

src/data-source/collection-browser-data-source.ts

Currently, because the target collection is not necessarily included in the PPS `collection_titles` map, it may be displayed as a bare identifier in facets & result tiles. We already have the correct title on the separate `collection_extra_info` branch of the response, so this PR just merges that into the title map when available.

WEBDEV-7323 Ensure target collection's title is shown in facets/results

---

src/collection-browser.ts
src/data-source/collection-browser-data-source-interface.ts
src/data-source/collection-browser-data-source.ts
test/collection-browser.test.ts
test/data-source/collection-browser-data-source.test.ts

Broadens the conditions under which manage view can be enabled w/ a larger result set, and adds a data source method to adjust how many pages are loaded accordingly. Also corrects the `manageModeChanged` event to only emit when its value is _actually changed_, not when it is first set to its initial value.

WEBDEV-7397 Improved flexibility for handling mange view

---

.github/workflows/pr-preview.yml

- `ubuntu-20.04` is now deprecated, we should use `ubuntu-latest` instead to prevent this in the future

Update GH runner for pr-preview workflow

---

test/collection-browser.test.ts
test/tile-stats.test.ts

Some of our unit tests have been failing both on unrelated features branches and on `main`, for reasons mostly unrelated to the actual behavior being tested. This PR updates them for greater reliability and ensure they are less susceptible to quirks of timing.

WEBDEV-7167 Fix broken unit tests

---

src/data-source/collection-browser-data-source-interface.ts
src/data-source/collection-browser-data-source.ts

When the management UI is opened, we attempt to load a larger first page of results, which entails resetting any pages that have been loaded in already. Currently this invalidates _all_ fetches in progress by the data source, including facet fetches.
However, since the facets will be the same with either result set, we do still want those fetches to succeed. This PR ensures we do not invalidate facet fetches when resetting the result pages for item management.

WEBDEV-7587 Do not purge ongoing facet requests when resetting pages

---

package.json
src/collection-browser.ts
src/data-source/collection-browser-data-source.ts
src/data-source/collection-browser-query-state.ts
src/models.ts
src/restoration-state-handler.ts
src/tiles/grid/item-tile.ts
src/tiles/grid/tile-stats.ts
src/tiles/list/tile-list-compact.ts
src/tiles/list/tile-list.ts
src/tiles/tile-mediatype-icon.ts
test/collection-browser.test.ts
test/mocks/mock-search-responses.ts
test/mocks/mock-search-service.ts
test/restoration-state-handler.test.ts
test/tiles/tile-mediatype-icon.test.ts
yarn.lock

Adds support for TV search filters on clip types, such as `only_quotes`. Also corrects the logic for when each clip type should be displayed, using fields newly available from the search service.

WEBDEV-7687 Support filters on TV clip types

---

src/tiles/hover/hover-pane-controller.ts

Currently tile hover panes are missing the window scroll amount in their positioning calculation. This PR adds the appropriate values to their top/left position so that they appear in the desired location when scrolling down the page.
Moreover, in some cases the hover pane controller attempts to call `showPopover` on elements that have already been disconnected from the DOM because of a component update. This PR guards against that by early-returning if the popover element is disconnected.

WEBDEV-7740 Ensure tile hover panes are correctly positioned & skip showing if disconnected

---

package.json
yarn.lock

Upgrades the `histogram-date-range` package to a version that correctly handles years 0-99.

WEBDEV-7745 Upgrade to alpha date picker version

---

package.json
src/collection-browser.ts
src/collection-facets/smart-facets/smart-facet-bar.ts
src/collection-facets/smart-facets/smart-facet-dropdown.ts
src/tiles/grid/styles/tile-grid-shared-styles.ts
src/tiles/tile-dispatcher.ts
yarn.lock

Two changes in preparation for the new search beta:
- Box shadows on tiles are currently always dark and thick. To allow more flexibility in how tiles are displayed in various contexts, this PR exposes two CSS vars that allow them to be customized more easily.
- The smart facets regain a text label, which is now customizable from outside the component.
- Clicking the default label of a smart facet dropdown now selects it immediately, rather than opening the dropdown menu (consistent with how the sort bar dropdowns function). Dropdown menus can still be opened by clicking the arrow.

WEBDEV-7768 Search beta: Tile box shadow customization & smart facet adjustments

---

src/collection-browser.ts
src/models.ts
src/sort-filter-bar/sort-filter-bar.ts
test/sort-filter-bar/sort-filter-bar.test.ts
tsconfig.json

TV searches do not require all the same sort options available, in particular since many of the date options are either not relevant or essentially the same for TV items.
This PR generalizes how the sort bar component is configured a bit, so that we can easily modify what sort options are available in bulk rather than via individual flags, and then ensures it is configured appropriately in the cases that require non-default sort options.

WEBDEV-7757 Adjust sort options shown for TV searches

---

src/app-root.ts
src/collection-browser.ts

The `facetPaneVisible` property currently only has an effect when `showSmartFacetBar` is enabled. However, there is little reason why these two properties need to be coupled that way. This PR allows `facetPaneVisible` to take effect regardless of whether smart facets are shown.

Allow `facetPaneVisible` prop to function without smart facets
