- src/tiles/grid/collection-tile.ts
> WEBDEV-5018: Restyled collection tile

- package.json
- src/collection-browser.ts
- src/models.ts
- src/tiles/grid/item-tile.ts
- src/tiles/list/tile-list-compact.ts
- src/tiles/list/tile-list-detail.ts
- yarn.lock
Add publicdate, reviewdate to model
Update to new search-service
WEBDEV-5166
> Webdev 5166 add dates

- src/utils/format-count.ts
- src/utils/format-date.ts
- test/utils/format-count.test.ts
- test/utils/format-date.test.ts
Created utils/formatDate and formatCount for proper formatting of dates and counts given format options. Unit tests.
WEBDEV-5177
> Add format count, date utilities, i8n

- src/tiles/list/tile-list.ts
Wrap label and value in div, stick in flex container as row
> Format line of dates

- src/mediatype-icon.ts
- src/tiles/list/tile-list.ts
Removed text for now. 
Popup/tooltip suggested -- will see how this is responded to.
> Move mediatype icon to right

- src/tiles/list/tile-list.ts
Add margin between thumbnail and content
Set inner component to inline-block
> Fix collection wrap

- src/tiles/grid/item-tile.ts
- src/waveform-thumbnail.ts
Changes:
- add waveform thumbnail view
TODO:
- determine if image loaded is waveform
> Waveform thumbnail

- src/collection-browser.ts
- src/tiles/list/tile-list.ts
Complete mobile view of detailed list view.
Convert collections links changing async component to async state and function
> Mobile list, collections as promise[]

- src/collection-browser.ts
Make sure when facets get moved we stay in "mobile" view
> Match facet mobile cutoff

- src/mediatype-icon.ts
- src/tiles/list/tile-list-compact.ts
- src/tiles/list/tile-list.ts
> Set list-only collection icon color

- src/tiles/grid/account-tile.ts
https://webarchive.jira.com/browse/WEBDEV-5288
> Offshoot Search: Account names should be truncated when too long

- src/collection-browser.ts
Solution summary: 
- Moved inline html into template method
- Created no-transition "preload" class
- Created toggle var to set "preload" class on loading, unset on user action
> Fix resize facet jitter

- package.json
https://webarchive.jira.com/browse/WEBDEV-5289
> Bump to v0.2.0

- src/styles/item-image-styles.ts
- src/tiles/item-image.ts
> Fix waveform height

- package.json
- yarn.lock
https://webarchive.jira.com/browse/WEBDEV-5266
> Offshoot : Collection browser layout broken for rendertron (?noscript=true) 

- package.json
- src/sort-filter-bar/sort-filter-bar.ts
https://webarchive.jira.com/browse/WEBDEV-5293
> Added title attribute on layout views

- src/mediatype/mediatype-config.ts
- src/tiles/list/tile-list-compact.ts
- src/tiles/list/tile-list.ts
- src/tiles/mediatype-icon.ts
from [PR#72](https://github.com/internetarchive/iaux-collection-browser/pull/72)
> Add mediatype icon color fix

- src/tiles/grid/tile-stats.ts
- src/tiles/mediatype-icon.ts
Reference: https://learn-the-web.algonquindesign.ca/topics/html-semantics-cheat-sheet/
> WEBDEV-5332 - Implement semantic HTML and add screen-reader only class

- src/collection-facets.ts
https://webarchive.jira.com/browse/WEBDEV-5357
> Refine design of negative facets

- package.json
- yarn.lock
(this helps offshoot properly build search page assets)
> histogram v bump - for ia-activity-indicator

- src/collection-browser.ts
- test/collection-browser.test.ts
- test/mocks/mock-search-responses.ts
- test/mocks/mock-search-service.ts
https://webarchive.jira.com/browse/WEBDEV-5417
> WEBDEV-5417 Search results quantity label doesn't pluralize correctly

- src/collection-browser.ts
- test/collection-browser.test.ts
Adding new property `searchContext` to better describe where the component is being used.
> Dynamic search context

- src/app-root.ts
- src/collection-facets/facets-template.ts
- src/collection-facets/more-facets-content.ts
- src/restoration-state-handler.ts
- test/restoration-state-handler.test.ts
- yarn.lock
> Merge main to search service

- src/collection-browser.ts
- src/styles/item-image-styles.ts
- src/tiles/grid/account-tile.ts
- src/tiles/grid/item-tile.ts
- src/tiles/grid/styles/tile-grid-shared-styles.ts
- src/tiles/image-block.ts
- src/tiles/item-image.ts
- src/tiles/tile-dispatcher.ts
- test/tiles/grid/account-tile.test.ts
https://webarchive.jira.com/browse/WEBDEV-5625
In this revision, I followed following coding structure, looking to have more suggestion on below structure.
- render()
- template getters
- other component lifecycle methods like update()
- other methods
- css
> Revised Patron Tile (UI) with flexy height

- src/app-root.ts
- src/collection-browser.ts
- src/models.ts
- src/styles/item-image-styles.ts
- src/tiles/collection-browser-loading-tile.ts
- src/tiles/grid/account-tile.ts
- src/tiles/grid/collection-tile.ts
- src/tiles/grid/item-tile.ts
- src/tiles/grid/styles/tile-grid-shared-styles.ts
- src/tiles/image-block.ts
- src/tiles/item-image.ts
- src/tiles/tile-dispatcher.ts
- src/utils/format-count.ts
- src/utils/format-unit-size.ts
- test/item-image.test.ts
- test/tiles/grid/collection-tile.test.ts
- test/utils/format-unit-size.test.ts
https://webarchive.jira.com/browse/WEBDEV-5626
> Revised Collection Tile (UI) with flexy height

- src/collection-browser.ts
- src/collection-facets.ts
The feedback button on the date picker is missing all of its necessary properties, causing it to error out when used. This PR ensures it receives all the properties it needs to function correctly.
> WEBDEV-5725 Fix date picker feedback button

- src/sort-filter-bar/alpha-bar.ts
> WEBDEV-5696 Add breakpoint on alphabar for small screen widths

- src/collection-facets/more-facets-content.ts
- src/collection-facets/more-facets-pagination.ts
- src/collection-facets/toggle-switch.ts
- test/collection-facets/toggle-switch.test.ts
This PR updates the styles of various elements on the More facets dialog for greater consistency and alignment with the design spec. E.g., matching the colors on text & buttons to those used elsewhere on the page.
> WEVDEV-5734 Update More facets dialog styles

- src/utils/format-date.ts
https://webarchive.jira.com/browse/WEBDEV-5766
> Date should be in UTC format on tiles

- src/sort-filter-bar/sort-filter-bar.ts
- src/utils/format-date.ts
https://webarchive.jira.com/browse/WEBDEV-5782
> Sort bar options should stay put when selected

- package.json
- yarn.lock
Also upgrades search-service and collection-name-cache dependencies.
> Bump version to 1.3.0

- package.json
- src/collection-browser.ts
- test/mocks/mock-search-responses.ts
- yarn.lock
The PPS now provides `collection_extra_info` for `collection_details` requests. This PR upgrades the search service version and pulls that new info into collection browser.
> WEBDEV-6174 Upgrade search service to receive collection info

- src/collection-browser.ts
- src/collection-facets.ts
- src/utils/analytics-events.ts
- test/collection-browser.test.ts
- test/collection-facets.test.ts
- test/mocks/mock-search-responses.ts
- test/mocks/mock-search-service.ts
The old collection page had a "Part of" section in the left sidebar which listed & linked to the parent collections. This PR adds that feature to the new page as well.
> WEBDEV-6227 Add "Part Of" section above facets

- src/app-root.ts
- src/collection-browser.ts
- add a named slot into the top of the facets column
- add div container with border and colored div for now to represent slot container
- add adjustable width and height variable for div slot container
- add checkbox toggle to show/hide the facet-top view under dev-tools toggle controls
[facet-top-container.gif](https://github.com/internetarchive/iaux-collection-browser/assets/1281581/d11802ce-3f8c-459b-bd0a-8f1bb8e4c04e)
Note: 
~~no need to create new version of npm package~~
will cut a new patch tag to update in offshoot
> Slot for facet-top template

- src/app-root.ts
- src/collection-browser.ts
https://webarchive.jira.com/browse/WEBDEV-6290
> Added slot for list header on collection-browser

- .github/workflows/ci.yml
- .github/workflows/gh-pages-main.yml
- .github/workflows/npm-publish.yml
- .github/workflows/pr-preview.yml
Build gives deprecated message.
Updated versions of checkout and setup-node.
webdev-6432
> Update workflows .yml versions

- package.json
- src/app-root.ts
- src/collection-browser.ts
- yarn.lock
https://webarchive.jira.com/browse/WEBDEV-6276
Description: let's add custom slot in collection-browser for result-cta-tile on ?tab=uploads and ?tab=web-archive tab so what we can a extra tile to upload new content.
> WEBDEV-6276 Added custom slot for result-cta-tiles

- src/app-root.ts
- src/collection-browser.ts
- src/sort-filter-bar/sort-filter-bar.ts
https://webarchive.jira.com/browse/WEBDEV-6535
> UI: <coll-brower> - add custom slot to add Upload button

- src/app-root.ts
- src/collection-browser.ts
- src/tiles/list/tile-list-compact.ts
https://webarchive.jira.com/browse/WEBDEV-6568
> WEBDEV-6568 Tweak loading tombstones for collection page compact list view

- src/app-root.ts
- src/collection-browser.ts
- src/manage/manage-bar.ts
Currently when you remove items from Lists tab, there is default label in manage-bar says `Select items to un-favorite`.
Let's just make it customization while using `<collection-browser>` so that we can pass custom message as well since we are going to use this multiple locations like removing fav- item from fav- collection, remove lists, uploads, collections etc.. from new profile page.
Reference to https://webarchive.jira.com/browse/WEBDEV-6680
> Customized manage views label while removing items

- src/collection-browser.ts
- src/manage/manage-bar.ts
- src/styles/ia-button.ts
- src/tiles/tile-dispatcher.ts
- test/collection-browser.test.ts
- test/manage/manage-bar.test.ts
https://webarchive.jira.com/browse/WEBDEV-6702
when you open manageView, the delete button should be disable initially. when you select items, it should turn to active state.
> Collection-Browser - toggle the Remove button in ManageView while while removing items

- package.json
- yarn.lock
Update version after review and QA
> Use ia-dropdown 1.3.8

- src/collection-browser.ts
https://webarchive.jira.com/browse/WEBDEV-6679
> Offshoot: suppress heading for list-compact mode when no result

- src/collection-browser.ts
- src/utils/analytics-events.ts
Adds analytics to specify whether the mobile or desktop layout has been loaded.
> Fire analytics for mobile/desktop view

- src/tiles/hover/hover-pane-controller.ts
- src/tiles/hover/tile-hover-pane.ts
- src/tiles/image-block.ts
- test/tiles/hover/tile-hover-pane.test.ts
https://webarchive.jira.com/browse/WEBDEV-6902
> Implement hover panel collection info header

- index.ts
Adds `TileDispatcher` type to the top-level package exports.
> Export tile-dispatcher component at top-level

- package.json
- src/models.ts
- test/collection-facets.test.ts
> Remove Availability facet from models list

- package.json
- src/collection-browser.ts
- yarn.lock
Adds slot for smart results to collection browser, along with styling ("All results" + extra spacing), that displays conditionally if `showSmartResults` is set to true.
> WEBDEV-7036 Integrate smart results into collection browser

- src/collection-facets/smart-facets/smart-facet-bar.ts
- src/collection-facets/smart-facets/smart-facet-button.ts
- src/collection-facets/smart-facets/smart-facet-dropdown.ts
- src/data-source/collection-browser-data-source.ts
Adds additional logging for smart facet bar experiments, and fixes a couple of small bugs around dropdown menu persistence.
> Logging & bugfixes for facet bar

- package.json
- src/app-root.ts
- src/collection-browser.ts
- src/manage/manage-bar.ts
- src/models.ts
- src/styles/ia-button.ts
- test/manage/manage-bar.test.ts
https://webarchive.jira.com/browse/WEBDEV-7209
> Add extra button for search page manage UI

- package.json
- yarn.lock
Upgrades to latest version of the feature feedback package.
> Upgrade feature-feedback dependency to 1.0.0
